### ISSUE TITLE
How to install package at Golang version 1.19.2 ? 

### ISSUE THREAD

**Issue by Gustavomurta** [go-ble/ble#103]
Hello, can anyone help me?
I can't install the package with golang version 1.9.2 (any S.O.). 
go version go1.19.2 windows/amd64

C:\Users\jgust\go>go get github.com/go-ble/ble
go: go.mod file not found in current directory or any parent directory.
        **'go get' is no longer supported outside a module.**
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

C:\Users\jgust\go>go install github.com/go-ble/ble@latest
go: downloading github.com/go-ble/ble v0.0.0-20220920230323-9a45bebfde4f
**package github.com/go-ble/ble is not a main package**

Honestly I don't know how to solve this. Thanks in advance, any help

**Comment by estutzenberger** [comment]
Is this still an issue for you? Generally you would `go mod init` for your project and then add required packages to that (e.g. this package) the `go.mod` file. Then run `go mod tidy` to install it locally for access by your code. If you are using this with Linux HCI, I'd recommend the version at https://github.com/rigado/ble as it has more releases and multiple bug fixes.

**Comment by Gustavomurta** [comment]
Hi Estut, 
I didn't realize that ble is a Golang Bluetooth Low Energy package for only Linux and Mac OS. Not for Windows. 
I'll test it on Linux, and then I'll answer you.
Thank you.
