### ISSUE TITLE
build fail caused by example

### ISSUE THREAD

**Issue by PinkD** [go-ble/ble#104]
When I build a program that uses this repo, it failed with this error:

```
$ go build . 
# github.com/go-ble/ble/examples/lib/dev
..\..\pkg\mod\github.com\go-ble\ble@v0.0.0-20230130210458-dd4b07d15402\examples\lib\dev\dev.go:9:9: undefined: DefaultDevice
```

platfom: win10 go1.20

**Comment by estutzenberger** [comment]
Unfortunately, Windows is not supported. This library as some support for Mac OS but is primarily written for use with Linux.
