### ISSUE TITLE
disconnect event problem

### ISSUE THREAD

**Issue by silviucm** [go-ble/ble#18]
Hi @moogle19  

This is in regards to the commit:
https://github.com/moogle19/ble/commit/619ee1f77e2de4a17af8786baa9c08b1c77e442e#diff-b4cc0f5fcbe12994ce01c868ee39ec66

Please note that changing c.param.Role comparison from **roleSlave** to **roleMaster** in this commit breaks  the following scenario for me:
- PC1 to PC2 connection (using two regular USB dongles), where PC1 is the Master (client), PC2 is the Slave (peripheral)
- PC1 connects to PC2, reads / writes something on PC2, and disconnects from PC2
- After disconnection, PC2 receives the handleDisconnectionComplete event 
- PC2 checks to see the role code, which is 1 (Slave), not 0 (Master). 
- Because of this PC2 does not send the HCI advertising re-enable command, and it is subsequently unable to receive new connections after the one initial connection.

**Comment by moogle19** [comment]
@silviucm Just rolled it back. Not sure why I changed it.
