### ISSUE TITLE
Unhandled events - OSX High Sierra

### ISSUE THREAD

**Issue by deadprogram** [go-ble/ble#3]
So, my last PR notwithstanding, there are still some additional ID under OS X "High Sierra" that need to be implemented.

Here is a log from a recent user:

```
2017/11/05 15:29:15 Unhandled event: xpc.Dict{"kCBMsgId":57, "kCBMsgArgs":xpc.Dict{"kCBMsgArgDeviceUUID":xpc.UUID{0x74, 0xfd, 0xa, 0xa, 0x3d, 0x80, 0x48, 0xa7, 0xb1, 0xd0, 0xd, 0x8e, 0xd9, 0xe8, 0xcf, 0xc1}, "kCBMsgArgATTMTU":23}}
2017/11/05 15:29:15 Unhandled event: xpc.Dict{"kCBMsgId":57, "kCBMsgArgs":xpc.Dict{"kCBMsgArgATTMTU":23, "kCBMsgArgDeviceUUID":xpc.UUID{0x74, 0xfd, 0xa, 0xa, 0x3d, 0x80, 0x48, 0xa7, 0xb1, 0xd0, 0xd, 0x8e, 0xd9, 0xe8, 0xcf, 0xc1}}}
2017/11/05 15:29:15 Unhandled event: xpc.Dict{"kCBMsgId":60, "kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0, "kCBMsgArgSupervisionTimeout":175, "kCBMsgArgDeviceUUID":xpc.UUID{0x74, 0xfd, 0xa, 0xa, 0x3d, 0x80, 0x48, 0xa7, 0xb1, 0xd0, 0xd, 0x8e, 0xd9, 0xe8, 0xcf, 0xc1}}}
2017/11/05 15:29:15 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgSupervisionTimeout":175, "kCBMsgArgDeviceUUID":xpc.UUID{0x74, 0xfd, 0xa, 0xa, 0x3d, 0x80, 0x48, 0xa7, 0xb1, 0xd0, 0xd, 0x8e, 0xd9, 0xe8, 0xcf, 0xc1}, "kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0}, "kCBMsgId":60}
```

Anyone have a link to where we can obtain docs on the latest ID mapping?

Also @moogle19 I like your latest updated cmd mapping in your own fork, please merge that into this fork so if/when I find the proper IDs I can add them in the same way.

**Comment by moogle19** [comment]
@deadprogram 
Maybe take a look at this [Noble PR](https://github.com/sandeepmistry/noble/pull/689)?
Seems to work for them.

**Comment by deadprogram** [comment]
Hi @moogle19 that was in fact what I used as the original conceptual basis for my PR. 

So I assume the author of that PR did not call all the same APIs as I have, for example did not use notifications?

**Comment by deadprogram** [comment]
Also, neither ID 57 nor 60 are ever mentioned in the Noble PR.

**Comment by deadprogram** [comment]
Hi @moogle19 any chance to get your most recent OSX refactorings into this repo, to use as a baseline for additional work?

**Comment by jacobrosenthal** [comment]
Some new xpcids for you all to try in #7

**Comment by moogle19** [comment]
@deadprogram @jacobrosenthal 
Are the xpcids complete now?
Can I close the issue?

**Comment by benji-bou** [comment]
Hello, 

Starting using my mac on "High Sierra" as a peripheral with go-ble. When connecting to a CentralManager on iOS (using CoreBluetooth). 
I received an Unhandled event: 54
Complete log is 

```Unhandled event: xpc.Dict{"kCBMsgId":54, "kCBMsgArgs":xpc.Dict{"kCBMsgArgDeviceUUID":xpc.UUID{0x2a, 0x65, 0xd5, 0x3f, 0xcc, 0x2f, 0x47, 0x6f, 0xab, 0x6f, 0xc4, 0xcb, 0x46, 0xe1, 0xcc, 0x73}, "kCBMsgArgServiceEndHandle":65535, "kCBMsgArgServiceStartHandle":10}}```

I don't find this event id in the xpcid.go file in darwin. 

Best

**Comment by jacobrosenthal** [comment]
Beyond this new 54 @benji-bou is reporting, Yeah nobody on the node side has found any new ids over the past months.

**Comment by benji-bou** [comment]
Hi, 

In fact I'm not on High Sierra. (I was sure I made the update but it seems not) I'm on Sierra in fact

Best
