### ISSUE TITLE
Cannot have multiple clients - because ble advertisements stop?

### ISSUE THREAD

**Issue by mehrvarz** [go-ble/ble#31]
Hi. I am using code similar to examples/basic/server/main.go. When ble.AdvertiseNameAndServices() is called, advertisements start broadcasting and clients can connect by picking them up. But advertisements do stop while a client is connected. As a result no other clients are able to connect. Is it possible to let the broadcasts continue while a client is connected? Should it (then) be possible to support multiple clients in parallel?

**Comment by estutzenberger** [comment]
At the moment, only one client at a time is supported. If you are able to submit a PR for the work to enable multiple client connections, I'd gladly welcome it!
