### ISSUE TITLE
Mojave blues...

### ISSUE THREAD

**Issue by txshawn** [go-ble/ble#46]
I know the Mac version is no longer being maintained, but I have a Gobot project I am working on in Mojave and I'm keen to keep this library going on Mac if I can help maintain it. Problem is that I'm on brick number 1 of this road that it seems many before me trod the entire thing to get through High Sierra.

Where I sit right now is with a utsname.Release of 18.6.0 on my Mac along with bluetoothd v6.0.12. I have the following unknown XPC IDs and am not entirely sure how to start digging in to help myself here. Any guidance from those battle-hardened souls who swore this off after High Sierra?

2019/06/21 12:49:39 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBAdvDataDeviceAddress":[]uint8{0x65, 0x1f, 0xe4, 0xce, 0x20, 0xd0}}, "kCBMsgId":38}
2019/06/21 12:49:39 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBAdvDataDeviceAddress":[]uint8{0x65, 0x1f, 0xe4, 0xce, 0x20, 0xd0}}, "kCBMsgId":38}
2019/06/21 13:00:15 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgATTMTU":23, "kCBMsgArgDeviceUUID":xpc.UUID{0xcd, 0xff, 0xd7, 0x42, 0xca, 0x56, 0x4a, 0x36, 0x92, 0x5b, 0xbe, 0x12, 0xc6, 0xfb, 0x8e, 0x43}}, "kCBMsgId":67}
2019/06/21 13:00:15 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgATTMTU":23, "kCBMsgArgDeviceUUID":xpc.UUID{0xcd, 0xff, 0xd7, 0x42, 0xca, 0x56, 0x4a, 0x36, 0x92, 0x5b, 0xbe, 0x12, 0xc6, 0xfb, 0x8e, 0x43}}, "kCBMsgId":67}
2019/06/21 13:00:16 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0, "kCBMsgArgDeviceUUID":xpc.UUID{0xcd, 0xff, 0xd7, 0x42, 0xca, 0x56, 0x4a, 0x36, 0x92, 0x5b, 0xbe, 0x12, 0xc6, 0xfb, 0x8e, 0x43}, "kCBMsgArgSupervisionTimeout":175}, "kCBMsgId":70}
2019/06/21 13:00:16 Unhandled event: xpc.Dict{"kCBMsgArgs":xpc.Dict{"kCBMsgArgConnectionInterval":18, "kCBMsgArgConnectionLatency":0, "kCBMsgArgDeviceUUID":xpc.UUID{0xcd, 0xff, 0xd7, 0x42, 0xca, 0x56, 0x4a, 0x36, 0x92, 0x5b, 0xbe, 0x12, 0xc6, 0xfb, 0x8e, 0x43}, "kCBMsgArgSupervisionTimeout":175}, "kCBMsgId":70}

**Comment by deadprogram** [comment]
Hello @txshawn see my comment https://github.com/go-ble/ble/issues/32#issuecomment-443496698

**Comment by txshawn** [comment]
Thanks, man. The only problem with that is that I'd have to rewrite the entire gobot ble implementation, which exceeds my skillset. Was hoping for a more "do this tedious thing we did last time because it sort of worked" bandaid.

**Comment by deadprogram** [comment]
To be clear, Gobot itself does not need to change. 

The changes needed are to go-ble's Darwin implementation located here:
https://github.com/go-ble/ble/tree/master/darwin

and goble's xpc implementation located here https://github.com/raff/goble/tree/master/xpc

that would need to use the native macOS code.

**Comment by txshawn** [comment]
Hmm. Ok, I guess I was overthinking it. Thanks, man!
