### ISSUE TITLE
The *darwin.Device type does not implement ble.DeviceOption

### ISSUE THREAD

**Issue by peterhellberg** [go-ble/ble#59]
Support for macOS was broken with the addition of the `SetConnectedHandler` and `SetDisconnectedHandler` methods to the `ble.DeviceOption` interface.

I’m aware that macOS isn’t actively maintained, but I thought it might be a good idea for it to at least compile.

(By doing something along these lines)

```diff
diff --git a/darwin/option.go b/darwin/option.go
index 1d86b7c..27d324f 100644
--- a/darwin/option.go
+++ b/darwin/option.go
@@ -5,8 +5,19 @@ import (
        "time"

        "github.com/go-ble/ble/linux/hci/cmd"
+       "github.com/go-ble/ble/linux/hci/evt"
 )

+// SetConnectedHandler sets handler to be called when new connection is established.
+func (d *Device) SetConnectedHandler(f func(evt.LEConnectionComplete)) error {
+       return errors.New("Not supported")
+}
+
+// SetDisconnectedHandler sets handler to be called on disconnect.
+func (d *Device) SetDisconnectedHandler(f func(evt.DisconnectionComplete)) error {
+       return errors.New("Not supported")
+}
+
 // SetPeripheralRole configures the device to perform Peripheral tasks.
 func (d *Device) SetPeripheralRole() error {
        d.role = 1
```

Unfortunately it seem like this doesn’t actually make this project work under macOS, so another idea would be to just remove the `darwin` package from this repo.

**Comment by estutzenberger** [comment]
Thanks for noting this. I suspect the travis build is not working correctly due to the introduction of go modules and so this issue was not caught prior to the PR merge which broke this build.

The mac os support relies on an interface, which, as far as I can tell, changes with every mac os version. The best way to support mac os would be to build a golang binding to CoreBluetooth but that's not something I am able to take on.

In addition, regarding the above, I think it's problematic that there are references to the linux packages within the darwin package. The original design probably intended them to be separate.

Are you interested in submitting a PR against this issue?

**Comment by peterhellberg** [comment]
Yes it seems like supporting macOS is tricky, mainly due to such changes as you mention between versions.

I’ll see what I can do.

**Comment by ginjaneer** [comment]
Sorry, I only meant a PR to fix the current main issue that was reported (build fails). 

Certainly if you want to take on mac os, that's up to you!

**Comment by estutzenberger** [comment]
Sorry, I only meant a PR to fix the current main issue that was reported (build fails).

Certainly if you want to take on mac os, that's up to you!

**Comment by peterhellberg** [comment]
Ok, it is a bit unfortunate that fixing the build issue as suggested doesn’t actually make the package work as it should. But I guess it is a slight improvement to have it build at all :)

I’ll open a PR when I get some time to do so.

**Comment by dwintergruen** [comment]
Is there any news about it? Or any way around it. Try to get sphero to work on Mac OS X with mojave.

	*Device does not implement ble.DeviceOption (missing SetConnectedHandler method)

**Comment by peterhellberg** [comment]
Unfortunately adding a “mocked” implementation of this interface for macOS will probably not make it actually work. There probably needs to be a new package developed for proper macOS support.

**Comment by magallardo** [comment]
Is the MacOs version still not working?  Please advise if there is a way to get this working.  Is any other library available for go?  I am willing to help if provided with an overview of what the problem is and possible solutions.  Thanks

**Comment by peterhellberg** [comment]
@magallardo My PR just adds stubs to make compiling the package work, it does not provide any functionality. I’ve (lightly) used https://github.com/raff/goble under macOS Mojave, maybe that can be an option for you?

**Comment by magallardo** [comment]
@peterhellberg Thanks for the pointer.  I have tried and was able to get it to work partially.  I am able to scan the peripherals, discover the peripherals, but when I call connect to one peripheral, I don't get any response back.  Were you able to connect to a peripheral?  Thanks again for your help.

**Comment by peterhellberg** [comment]
@magallardo I've only used it to receive `ManufacturerData` in BLE announcements with my https://github.com/peterhellberg/ruuvitag package.
