### ISSUE TITLE
SMP "Just Works"

### ISSUE THREAD

**Issue by gesaleh** [go-ble/ble#6]
I see that the smp.go is the same as the original fork so this doesn't support any pairing feature ?
I would like to use just works noinputkeydisplay

**Comment by gesaleh** [comment]
Any news about this?

Thanks

**Comment by estutzenberger** [comment]
I'm not sure if this is needed, but SMP Just Works is currently be enabled in our Rigado fork. That said, I'm am not sure yet when that will be pull back into this mainline repository.
