### ISSUE TITLE
Get MAC address of hci

### ISSUE THREAD

**Issue by wz2b** [go-ble/ble#80]
```d, err := dev.NewDevice("hci0")```

Does this API allow me to get the hardware address of the interface itself?

**Comment by estutzenberger** [comment]
Yes, you can call `d.Address()` to get the MAC address of the attached radio.

**Comment by raphaelpereira** [comment]
![image](https://user-images.githubusercontent.com/1225171/215332210-df15f5f3-0331-4fc9-9823-a10c45305e35.png)

Interface doesn't have Address() anymore (if it had once). How to do it now?

**Comment by estutzenberger** [comment]
Hmm, that is strange. I don't know the history here but device.go in the linux package _does_ have the function. Why it is not in the interface... I have no idea. I'm not sure I'll have time to add it anytime soon but if someone wants to put in a PR for it, I can review it.

Alternatively, we do have it in our maintained version here: github.com/rigado/ble
