### ISSUE TITLE
is it useable for android?

### ISSUE THREAD

**Issue by MatejMagat305** [go-ble/ble#87]
Hi I m coding in https://github.com/fyne-io/fyne, and it can run on android, it this library suitable for android?

**Comment by estutzenberger** [comment]
I'm not sure. I don't have any experience running Golang on Android or using this library on Android. If the Golang code can run and you have access to a UART device which runs an HCI bluetooth stack then, it should work.

**Comment by Solander** [comment]
@MatejMagat305 Did you get this working?
