### ISSUE TITLE
Advertisement.LocalName() returns empty string if Name is sent in scan response

### ISSUE THREAD

**Issue by LassiHeikkila** [go-ble/ble#96]
I'm working with a BLE beacon (Teltonika EYE Beacon) which sends LocalName in scan response.
It seems like `go-ble/ble` only reads the name from the initial advertisement packet.

I don't know if its desired behaviour to make this change, but reading the name from scan response is a fairly minor change:

Existing code (https://github.com/go-ble/ble/blob/master/linux/hci/adv.go#L54-L57):
```go
// LocalName returns the LocalName of the remote peripheral.
func (a *Advertisement) LocalName() string {
	return a.packets().LocalName()
}
```

Proposed code:
```go
// LocalName returns the LocalName of the remote peripheral.
func (a *Advertisement) LocalName() string {
	if a.packets().LocalName() != "" {
		return a.packets().LocalName()
	}

	if a.sr != nil && a.sr.LocalName() != "" {
		return a.sr.LocalName()
	}

	return ""
}
```

Please let me know if you would like me to make a proper PR about this change to integrate it to this library.

**Comment by estutzenberger** [comment]
A PR would be greatly appreciated! 

I believe this might fixed in our version at github.com/rigado/ble because it concatenates the advertisement and scan response data and then processes the payload.
